# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

deploy:
  - provider: script
    script: ./docker-build --verbose --config .travis.yml --release github
    skip_cleanup: true
    on:
      tags: true
      condition: "${TRAVIS_TAG} =~ ^v.*$ && ${DISTRO} =~ ^fedora.*$"

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:testing"
  - DISTRO="fedora:30"
  - DISTRO="ubuntu:19.04"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/mate-settings-daemon
    - dbus-glib
    - gcc
    - git
    - intltool
    - libcanberra
    - libmatekbd
    - libmatemixer
    - libnotify
    - make
    - mate-common
    - mate-desktop
    - nss
    - polkit
    - pulseaudio
    - python
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-settings-daemon
    - git
    - libcanberra-gtk3-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libfontconfig1-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libmatekbd-dev
    - libmatemixer-dev
    - libnotify-dev
    - libnss3-dev
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-dev
    - libpulse-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxext-dev
    - libxi-dev
    - libxklavier-dev
    - libxrandr-dev
    - libxt-dev
    - make
    - mate-common
    - x11proto-kb-dev

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-settings-daemon.git
    - dbus-glib-devel
    - dconf-devel
    - desktop-file-utils
    - gcc
    - git
    - gtk3-devel
    - iso-codes-devel
    - libSM-devel
    - libXxf86misc-devel
    - libcanberra-devel
    - libmatekbd-devel
    - libmatemixer-devel
    - libnotify-devel
    - make
    - mate-common
    - mate-desktop-devel
    - nss-devel
    - polkit-devel
    - pulseaudio-libs-devel
    - redhat-rpm-config

  ubuntu:
    - git
    - libcanberra-gtk3-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libfontconfig1-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libmatekbd-dev
    - libmatemixer-dev
    - libnotify-dev
    - libnss3-dev
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-dev
    - libpulse-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxext-dev
    - libxi-dev
    - libxklavier-dev
    - libxrandr-dev
    - libxt-dev
    - make
    - mate-common
    - x11proto-kb-dev

variables:
  - CFLAGS="-Wall -Werror=format-security"

configures:
  autotools:
    - --prefix=/usr
    - --enable-pulse

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  - bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-settings-daemon-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
