# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

# Use travis branch for test.
#branches:
#  only:
#  - travis

before_install:
  - curl -L -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/travis/travis/docker-build
  - chmod +x docker-build

install:
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

env:
  - DISTRO="base/archlinux"
  - DISTRO="debian:sid"
  - DISTRO="fedora:29"
  - DISTRO="ubuntu:18.10"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/mate-settings-daemon
    - dbus-glib
    - gcc
    - git
    - intltool
    - libcanberra
    - libmatekbd
    - libmatemixer
    - libnotify
    - make
    - mate-common
    - mate-desktop
    - nss
    - polkit
    - pulseaudio
    - python

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-settings-daemon
    - git
    - libcanberra-gtk3-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libfontconfig1-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libmatekbd-dev
    - libmatemixer-dev
    - libnotify-dev
    - libnss3-dev
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-dev
    - libpulse-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxext-dev
    - libxi-dev
    - libxklavier-dev
    - libxrandr-dev
    - libxt-dev
    - make
    - mate-common
    - x11proto-kb-dev

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-settings-daemon.git
    - dbus-glib-devel
    - dconf-devel
    - desktop-file-utils
    - gcc
    - git
    - gtk3-devel
    - iso-codes-devel
    - libSM-devel
    - libXxf86misc-devel
    - libcanberra-devel
    - libmatekbd-devel
    - libmatemixer-devel
    - libnotify-devel
    - make
    - mate-common
    - mate-desktop-devel
    - nss-devel
    - polkit-devel
    - pulseaudio-libs-devel
    - redhat-rpm-config

  ubuntu:
    # Same as debian
    - git
    - libcanberra-gtk3-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libfontconfig1-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libmatekbd-dev
    - libmatemixer-dev
    - libnotify-dev
    - libnss3-dev
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-dev
    - libpulse-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxext-dev
    - libxi-dev
    - libxklavier-dev
    - libxrandr-dev
    - libxt-dev
    - make
    - mate-common
    - x11proto-kb-dev

variables:
  - CFLAGS="-Wall -Werror=format-security"

configures:
  autotools:
    - --prefix=/usr
    - --enable-pulse

before_scripts:
  # These scripts should keep silent.
  - cd ${START_DIR}
  - '[ -f mate-desktop-1.21.2.tar.xz ] || curl -Ls -o mate-desktop-1.21.2.tar.xz http://pub.mate-desktop.org/releases/1.21/mate-desktop-1.21.2.tar.xz'
  - tar xf mate-desktop-1.21.2.tar.xz
  - cd mate-desktop-1.21.2
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu  >/dev/null 2>&1
  - else
  -     ./configure --prefix=/usr >/dev/null 2>&1
  - fi
  - make > /dev/null 2>&1
  - make install >/dev/null 2>&1

after_scripts:
  - make distcheck > /dev/null
    # It will fail on debian, so it always returns 0, but can see the error message.
  - 'if [ $? -ne 0 ];then RED="\033[0;31m"; NC="\033[0m"; printf "${RED}!!! ERROR: Run make distcheck failed.${NC}\n"; fi'
