subdir('common')

subdir('a11y-keyboard')
subdir('a11y-settings')
subdir('background')
subdir('clipboard')
subdir('datetime')
subdir('dummy')
subdir('housekeeping')
subdir('keybindings')
subdir('keyboard')
subdir('media-keys')
subdir('mpris')
subdir('mouse')

if have_smartcard_support
  subdir('smartcard')
endif

if have_rfkill
  subdir('rfkill')
endif

subdir('sound')
subdir('typing-break')
subdir('xrandr')
subdir('xrdb')
subdir('xsettings')

if have_wayland
  subdir('wlrandr')
endif
