.\" MATE manpages
.\" msd-datetime-mechanism -man
.\"
.TH msd-datetime-mechanism 1 "Oct 2014" "" "MATE-SETTINGS-DAEMON"
.SH NAME
msd-datetime-mechanism \- set system time via D-Bus
.SH SYNOPSIS
msd-datetime-mechanism
.SH DESCRIPTION
The \fImsd-datetime-mechanism\fR is used for setting the system time via D-Bus.
.
\fImsd-datetime-mechanism\fR is a D-Bus wrapper that gets executed via D-Bus with root privileges.
The execution of \fImsd-datetime-mechanism\fR gets triggered via the MATE clock applet.
.SH AUTHOR
This manual page has been written by Vangelis Mouhtsis <vangelis@gnugr.org> and Mike Gabriel <mike.gabriel@das-netzwerkteam.de>.
It has been originally written for the Debian project (but may be used by others).
