.\" MATE manpages
.\" msd-datetime-mechanism -man
.\"
.TH msd-locate-pointer 1 "Oct 2014" "" "MATE-SETTINGS-DAEMON"
.SH NAME
msd-locate-pointer \- create ripples around mouse pointer
.SH SYNOPSIS
msd-locate-pointer
.SH DESCRIPTION
The \fImsd-locate-pointer\fR utility is a program that creates ripples (like throwing a stone into water)
around the mouse pointer. This helps to locate the position of the mousepointer.
.PP
With \fImate-settings-daemon\fR i is possible to assign a hotkey for evoking
the \fImsd-locate-pointer\fR command.
.SH AUTHOR
This manual page has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de>.
It has been originally written for the Debian project (but may be used by others)